version: "1.0"
info:
  model: int-scaffold
packages:
- name: Test1706Project
  gitServerName: PT
  gitUrl: https://github.com/Pratibha0224
  gitUsername: Pratibha0224
  gitBranch: main
services:
- serviceName: project.test1706.integrations:testSvc
  packages:
  - name: Test1706Project
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.1.0.0.2067
